# Generated by Django 4.2.7 on 2023-11-30 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidadAguaApp', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Indicadores',
        ),
        migrations.DeleteModel(
            name='muestras',
        ),
        migrations.DeleteModel(
            name='proyectos',
        ),
        migrations.DeleteModel(
            name='proyectos_muestra',
        ),
        migrations.DeleteModel(
            name='usuarios',
        ),
        migrations.DeleteModel(
            name='usuarios_proyectos',
        ),
    ]
