# Generated by Django 4.2.7 on 2023-11-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calidadAguaApp', '0005_delete_indicadores_delete_muestras_delete_proyectos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductividad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('orp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('oxigeno_disuelto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_oxigeno', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profundidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('salinidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('solidos_suspendidos_totales', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('transparencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('conductividad_unidad_medida', models.CharField(max_length=3)),
                ('muestra_id', models.CharField(max_length=3)),
                ('orp_unidad_medida', models.CharField(max_length=3)),
                ('oxigeno_disuelto_unidad_medida', models.CharField(max_length=3)),
                ('ph_unidad_medida', models.CharField(max_length=3)),
                ('porcentaje_oxigeno_unidad_medida', models.CharField(max_length=3)),
                ('profundidad_unidad_medida', models.CharField(max_length=3)),
                ('salinidad_unidad_medida', models.CharField(max_length=3)),
                ('solidos_suspendidos_totales_unidad_medida', models.CharField(max_length=3)),
                ('temperatura_unidad_medida', models.CharField(max_length=3)),
                ('transparencia_unidad_medida', models.CharField(max_length=3)),
                ('id_indicadores', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='muestras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=9, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=9, max_digits=10)),
                ('fecha', models.DateField()),
                ('numero', models.IntegerField()),
                ('indicador_id', models.CharField(max_length=50)),
                ('laboratorio', models.CharField(max_length=50)),
                ('proyecto_id', models.CharField(max_length=50)),
                ('id_muestras', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=9, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=9, max_digits=10)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('localidades', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('proveedor', models.CharField(max_length=50)),
                ('tipo_recurso', models.CharField(max_length=50)),
                ('usuario_id', models.CharField(max_length=50)),
                ('zona', models.CharField(max_length=50)),
                ('id_proyectos', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='proyectos_muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muestra_id', models.CharField(max_length=50)),
                ('proyecto_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
                ('apellido', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('identificacion', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('passsword', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('id_usuarios', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios_proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyectos_id', models.CharField(max_length=50)),
                ('usuario_id', models.CharField(max_length=50)),
            ],
        ),
    ]
